context:
  version: "0.14.0"

package:
  name: turm
  version: ${{ version }}

source:
  url: https://github.com/karimknaebel/turm/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 6f1404336ba91be8b16a17f35cc3d24bce29538c1120005787d6abdb41d01536

build:
  number: 0
  skip:
    - not linux
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
      # Default to no cross-compile
      - export TURM="${PREFIX}/bin/turm"

      - if: target_platform != build_platform
        then:
          # Need to compile for the build_platform arch
          - cargo auditable install --locked --no-track --bins --root ${BUILD_PREFIX} --path .
          - export TURM="${BUILD_PREFIX}/bin/turm"

      # Install bash, zsh, and fish completions
      - mkdir -p ${PREFIX}/share/bash-completion/completions
      - ${TURM} completion bash > ${PREFIX}/share/bash-completion/completions/turm
      - mkdir -p ${PREFIX}/share/zsh/site-functions
      - ${TURM} completion zsh > ${PREFIX}/share/zsh/site-functions/_turm
      - mkdir -p ${PREFIX}/share/fish/vendor_completions.d
      - ${TURM} completion fish > ${PREFIX}/share/fish/vendor_completions.d/turm.fish

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - package_contents:
      strict: true
      bin:
        - turm
      files:
        - share/bash-completion/completions/turm
        - share/zsh/site-functions/_turm
        - share/fish/vendor_completions.d/turm.fish
  - script: turm --help

about:
  homepage: https://github.com/karimknaebel/turm
  summary: TUI for the Slurm Workload Manager
  description: |
    A text-based user interface (TUI) for the Slurm Workload Manager, which
    provides a convenient way to manage your cluster jobs.
  license: MIT
  license_file:
    - LICENSE
  documentation: https://github.com/karimknaebel/turm
  repository: https://github.com/karimknaebel/turm

extra:
  recipe-maintainers:
    - matthewfeickert
